version: '3'

services: 

  app:
    build: 
      context: ./node
    image: antoniocmoura/node-app  
    container_name: app
    networks: 
      - node-network
    volumes: 
      - ./node:/usr/src/app
    tty: true
    ports: 
      - "3000:3000"
    depends_on: 
       - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true    
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network
    ports: 
      - "3306:3306"  

  nginx:
    build: 
      context: ./nginx
    image: antoniocmoura/nginx
    container_name: nginx
    networks: 
      - node-network
    ports: 
      - "8080:80" 

networks: 
  node-network:
    driver: bridge      